import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { Ionicons } from '@expo/vector-icons';
import * as Crypto from 'expo-crypto';
import * as SecureStore from 'expo-secure-store';
import Button from '../components/ui/Button';
import Colors from '../constants/colors';
import { getApiErrorMessage } from '../services/api';
import { scannerService } from '../services/scanner.service';
import { ScannerSession } from '../types/Scanner';

const DEVICE_KEY = 'taphoa.remote-scanner.device-id';
export default function RemoteScanner() {
  const [permission, requestPermission] = useCameraPermissions(); const [code, setCode] = useState(''); const [session, setSession] = useState<ScannerSession | null>(null); const [deviceId, setDeviceId] = useState(''); const [manual, setManual] = useState(''); const [busy, setBusy] = useState(false); const [locked, setLocked] = useState(false); const [feedback, setFeedback] = useState('');
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; void (async () => { let id = await SecureStore.getItemAsync(DEVICE_KEY); if (!id) { id = Crypto.randomUUID(); await SecureStore.setItemAsync(DEVICE_KEY, id); } if (mounted.current) setDeviceId(id); })(); return () => { mounted.current = false; if (session && deviceId) void scannerService.disconnect(session.sessionId, deviceId).catch(() => undefined); }; }, [session?.sessionId, deviceId]);

  const join = async () => { if (code.trim().length < 6 || !deviceId) return; setBusy(true); try { setSession(await scannerService.joinSession(code.trim().toUpperCase(), deviceId)); setFeedback('Đã kết nối. Hướng camera vào mã vạch.'); } catch (e) { Alert.alert('Không thể kết nối', getApiErrorMessage(e, 'Mã ghép nối không hợp lệ.')); } finally { setBusy(false); } };
  const publish = async (barcode: string) => { if (!session?.scannerToken || !barcode.trim() || locked) return; setLocked(true); try { await scannerService.publish(session.sessionId, barcode.trim(), deviceId, session.scannerToken); setFeedback(`Đã gửi mã ${barcode.trim()}`); setManual(''); } catch (e) { setFeedback(getApiErrorMessage(e, 'Không gửi được mã vạch.')); } finally { setTimeout(() => mounted.current && setLocked(false), 1200); } };
  const disconnect = async () => { if (session) await scannerService.disconnect(session.sessionId, deviceId).catch(() => undefined); setSession(null); setFeedback(''); };

  if (!session) return <View style={styles.setup}><View style={styles.mark}><Ionicons name="phone-portrait-outline" size={29} color={Colors.primary} /></View><Text style={styles.eyebrow}>MÁY QUÉT PHỤ</Text><Text style={styles.title}>Kết nối với máy bán hàng</Text><Text style={styles.note}>Nhập mã 6 ký tự đang hiển thị trên màn hình bán hàng hoặc web-admin. Thiết bị chỉ cần đăng nhập vào hệ thống.</Text><Text style={styles.label}>Mã ghép nối</Text><TextInput value={code} onChangeText={(v) => setCode(v.replace(/[^a-zA-Z0-9]/g, '').slice(0, 6).toUpperCase())} autoCapitalize="characters" autoCorrect={false} maxLength={6} placeholder="A1B2C3" style={styles.codeInput} /><Button title="Kết nối máy quét" size="lg" loading={busy || !deviceId} disabled={code.length < 6} onPress={join} /></View>;

  const cameraReady = permission?.granted;
  return <View style={styles.page}>
    <View style={styles.top}><View><Text style={styles.connected}>ĐÃ KẾT NỐI</Text><Text style={styles.session}>Phiên {session.pairingCode}</Text></View><Pressable accessibilityLabel="Ngắt kết nối" style={styles.close} onPress={disconnect}><Ionicons name="close" size={24} color={Colors.text} /></Pressable></View>
    {!permission ? <View style={styles.center}><ActivityIndicator color={Colors.primary} /></View> : !cameraReady ? <View style={styles.center}><Ionicons name="camera-outline" size={36} color={Colors.primary} /><Text style={styles.cameraTitle}>Cần quyền camera</Text><Text style={styles.note}>Camera chỉ hoạt động trong màn hình quét này. Bạn vẫn có thể nhập mã thủ công bên dưới.</Text><Button title="Cho phép camera" onPress={requestPermission} /></View> : <View style={styles.cameraWrap}><CameraView style={StyleSheet.absoluteFill} facing="back" barcodeScannerSettings={{ barcodeTypes: ['ean13', 'ean8', 'code128', 'code39', 'upc_a', 'upc_e', 'qr'] }} onBarcodeScanned={locked ? undefined : ({ data }) => void publish(data)} /><View pointerEvents="none" style={styles.frame} /><Text style={styles.hint}>Đưa mã vạch vào giữa khung</Text></View>}
    <View style={styles.bottom}>{!!feedback && <Text style={[styles.feedback, feedback.startsWith('Đã gửi') && styles.feedbackOk]}>{feedback}</Text>}<Text style={styles.label}>Nhập mã thủ công</Text><View style={styles.manualRow}><TextInput value={manual} onChangeText={setManual} placeholder="Mã vạch" keyboardType="number-pad" style={styles.input} /><Button title="Gửi" disabled={!manual.trim() || locked} onPress={() => publish(manual)} /></View></View>
  </View>;
}
const styles = StyleSheet.create({ setup: { flex: 1, justifyContent: 'center', padding: 26, backgroundColor: Colors.background }, page: { flex: 1, backgroundColor: Colors.black }, mark: { width: 60, height: 60, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primarySoft, marginBottom: 20 }, eyebrow: { color: Colors.primary, fontSize: 11, letterSpacing: 1.5, fontWeight: '900' }, title: { color: Colors.text, fontSize: 27, lineHeight: 33, fontWeight: '900', marginTop: 5 }, note: { color: Colors.textSecondary, textAlign: 'center', lineHeight: 21, marginVertical: 14 }, label: { color: Colors.text, fontWeight: '800', marginBottom: 8, marginTop: 14 }, codeInput: { minHeight: 62, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, backgroundColor: Colors.surface, color: Colors.text, textAlign: 'center', fontSize: 25, fontWeight: '900', letterSpacing: 7, marginBottom: 16 }, top: { padding: 18, paddingTop: 22, backgroundColor: Colors.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, connected: { color: Colors.success, fontSize: 10, letterSpacing: 1.2, fontWeight: '900' }, session: { color: Colors.text, fontWeight: '800', marginTop: 3 }, close: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, cameraWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' }, frame: { width: '82%', height: 170, borderRadius: 18, borderWidth: 2, borderColor: Colors.white }, hint: { position: 'absolute', bottom: 25, color: Colors.white, fontWeight: '800', backgroundColor: 'rgba(0,0,0,0.55)', paddingHorizontal: 13, paddingVertical: 8, borderRadius: 10 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30, backgroundColor: Colors.background }, cameraTitle: { color: Colors.text, fontWeight: '900', fontSize: 19, marginTop: 12 }, bottom: { padding: 18, paddingBottom: 26, backgroundColor: Colors.surface }, feedback: { color: Colors.danger, fontWeight: '700', marginBottom: 5 }, feedbackOk: { color: Colors.success }, manualRow: { flexDirection: 'row', gap: 10 }, input: { flex: 1, minHeight: 50, borderWidth: 1, borderColor: Colors.border, borderRadius: 11, paddingHorizontal: 13, color: Colors.text, backgroundColor: Colors.surface } });
